pywb:
    build: ./pywb
#    image: ikreymer/pywb:dev
    restart: always
    links:
        - redis
        - memento_agg

    volumes:
        - ./pywb:/webarchive
        - './pywb/uwsgi.ini:/uwsgi/uwsgi.ini'

memento_agg:
    image: ibnesayeed/memgator
    restart: always

    command: server --arcs=/archives.json -t 15s -r 30s -T 30s
    ports:
        - 1208:1208

    volumes:
        - ./archives.json:/archives.json

redis:
    image: redis:latest
    restart: always

app:
    build: ./app
    restart: always
    links:
        - redis

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./app/browser:/browser

    environment:
        - SCREEN_WIDTH=1200
        - SCREEN_HEIGHT=800

    ports:
        - 9020:9020
