pywb:
    build: ./pywb
    restart: always
    links:
        - redis

redis:
    image: redis:latest
    restart: always

app:
    build: ./app
    restart: always
    links:
        - redis

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./app/browser:/browser

    ports:
        - 9020:9020
