pywb:
    build: ./pywb
    restart: always
    environment:
        - ARCHIVE_JSON=/archives.json

    volumes:
        - ${ARCHIVE_JSON}:/archives.json

    # for init order
    volumes_from:
        - redis

memgator:
    image: ibnesayeed/memgator:master
    restart: always

    command: --arcs=/archives.json server
    ports:
        - 1209:1208

    volumes:
        - ${ARCHIVE_JSON}:/archives.json

nginx:
    build: ./nginx
    restart: always
    volumes:
#        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/cache:/cache
#        - ./app/static:/static

    volumes_from:
        - app

    ports:
        - 80:80
        - 1208:1208
#        - 1210:1210

redis:
    image: redis:latest
    restart: always

shared_data:
    image: python:2.7
    command: python -i
    volumes:
        - ./shareddata:/shareddata
        - ./app/browser_app.py:/app/app.py
        - ./app/run_browser:/usr/bin/run_browser

app:
    build: ./app
    restart: always

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    environment:
        - SCREEN_WIDTH=1024
        - SCREEN_HEIGHT=768

    ports:
        - 9020:9020

    # for init order
    volumes_from:
        - redis
