pywb:
    build: ./pywb
    restart: always
#    environment:
#        - ARCHIVE_JSON=${ARCHIVE_JSON}

#    volumes:
#        - ./archives.json:/archives.json

#memgator:
#    image: ibnesayeed/memgator:master
#    restart: always

#    command: --arcs=${ARCHIVE_JSON} server
#    ports:
#        - 1208:1208

#    volumes:
#        - ./archives.json:/archives.json

redis:
    image: redis:latest
    restart: always

shared_data:
    image: python:2.7
    command: python -i
    volumes:
        - ./shareddata:/shareddata

app:
    build: ./app
    restart: always

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    environment:
        - SCREEN_WIDTH=1024
        - SCREEN_HEIGHT=768

    ports:
        - 9020:9020
