pywb:
    build: ./pywb
    restart: always
    links:
        - redis
        - memgator

    environment:
        - ARCHIVE_JSON=http://webenact.rhizome.org/collinfo.json
    #volumes:
    #    - ./archives.json:/archives.json

memgator:
#    image: ibnesayeed/memgator
    image: ikreymer/memgator
    restart: always

    command: --arcs=http://webenact.rhizome.org/collinfo.json server
    ports:
        - 1208:1208

    #volumes:
    #    - ./archives.json:/archives.json

redis:
    image: redis:latest
    restart: always

shared_data:
    image: python:2.7
    command: python -i
    volumes:
        - ./shareddata:/shareddata

app:
    build: ./app
    restart: always
    links:
        - redis

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    environment:
        - SCREEN_WIDTH=1200
        - SCREEN_HEIGHT=800

    ports:
        - 9020:9020
