
collections:

    # For Single Archive Collections: Specify CDX Path, url template and name
    single_archive:
        index_paths: 'http://web.archive.org/cdx/search/cdx'
        archive_template: 'http://web.archive.org/web/{timestamp}id_/{url}'
        archive_name: 'Internet Archive'

        wb_handler_class: !!python/name:archivereplayview.ReplayHandler


    # Memento Aggregator Collection: Specify paths to Timegate, Timemap
    memento_reconstruct:
        index_paths:
            # for LANL aggregator
            #timegate: http://timetravel.mementoweb.org/api/json/
            #timemap:  http://labs.mementoweb.org/timemap/json/

            # for local aggregator
            timegate: http://netcapsule_nginx_1:1208/timenav/json/
            timemap: http://netcapsule_nginx_1:1208/timemap/json/

        server_cls: !!python/name:mementoquery.MementoIndexServer

        wb_handler_class: !!python/name:archivereplayview.MementoHandler

#        fallback: live

    live:
        index_paths: $liveweb

# Specify memento archivelist XML
#memento_archive_xml: 'http://labs.mementoweb.org/aggregator_config/archivelist.xml'
#memento_archive_json: '/archives.json'
memento_archive_json: $ARCHIVE_JSON

reverse_proxy_prefix: http://netcapsule_nginx_1:1210/

buffer_response: false
urlrewriter_class: !!python/name:archivereplayview.ReUrlRewriter

enable_cdx_api: true
framed_replay: false

redis_url: redis://netcapsule_redis_1:6379/0

enable_http_proxy: true

redir_to_exact: false


proxy_options:
    enable_https_proxy: true

    # Select one of these
    #use_default_coll: 'single_archive'
    use_default_coll: 'memento_reconstruct'

    cookie_resolver: ip
    use_client_rewrite: false
    use_banner: false
